services:
  rsync:
    image: ghcr.io/nabeken/docker-volume-container-rsync:latest@sha256:72f786f41aa7c340b73518c94917217f3b9e04f540d2ee12a55f5d24abf3401a
    volumes:
      - vol:/docker
    ports:
      - "10873:873"

  sink:
    image: ghcr.io/nabeken/docker-smtp-sink:action-local-test
    volumes:
      - vol:/sink
    ports:
      - "10025:10025"
    command: ["-v", "-h", "mx.example.com", "-m", "100", "-d", "/sink/", ":10025", "100"]

volumes:
  vol:
