services:
  rsync:
    image: ghcr.io/nabeken/docker-volume-container-rsync:latest@sha256:adc5ed434a99b7865124a307bdbc014ce28b9cdfd16209c027255833c493abc0
    volumes:
      - vol:/docker
    ports:
      - "10873:873"

  sink:
    image: ghcr.io/nabeken/docker-smtp-sink:action-local-test
    volumes:
      - vol:/sink
    ports:
      - "10025:10025"
    command: ["-v", "-h", "mx.example.com", "-m", "100", "-d", "/sink/", ":10025", "100"]

volumes:
  vol:
