services:
  rsync:
    image: ghcr.io/nabeken/docker-volume-container-rsync:latest@sha256:c4b7ca43923f46a8f49e73e82af60aa3202937891798faef99b35b67b0ccbfe4
    volumes:
      - vol:/docker
    ports:
      - "10873:873"

  sink:
    image: ghcr.io/nabeken/docker-smtp-sink:action-local-test
    volumes:
      - vol:/sink
    ports:
      - "10025:10025"
    command: ["-v", "-h", "mx.example.com", "-m", "100", "-d", "/sink/", ":10025", "100"]

volumes:
  vol:
