services:
  rsync:
    image: ghcr.io/nabeken/docker-volume-container-rsync:latest@sha256:36236d00fee759ee76addb153b57367d83a0fd045bbfbad4549244790538da6a
    volumes:
      - vol:/docker
    ports:
      - "10873:873"

  sink:
    image: ghcr.io/nabeken/docker-smtp-sink:action-local-test
    volumes:
      - vol:/sink
    ports:
      - "10025:10025"
    command: ["-v", "-h", "mx.example.com", "-m", "100", "-d", "/sink/", ":10025", "100"]

volumes:
  vol:
