services:
  rsync:
    image: ghcr.io/nabeken/docker-volume-container-rsync:latest@sha256:4d3afb1130f612388a4dc0dfe9bc1be8c5be67aa6374dcb22f4220b298d62246
    volumes:
      - vol:/docker
    ports:
      - "10873:873"

  sink:
    image: ghcr.io/nabeken/docker-smtp-sink:action-local-test
    volumes:
      - vol:/sink
    ports:
      - "10025:10025"
    command: ["-v", "-h", "mx.example.com", "-m", "100", "-d", "/sink/", ":10025", "100"]

volumes:
  vol:
