services:
  rsync:
    image: ghcr.io/nabeken/docker-volume-container-rsync:latest@sha256:cc55f48b919abc776686b1e878ef69469ea1ac8d53e91946820fb5ef74259740
    volumes:
      - vol:/docker
    ports:
      - "10873:873"

  sink:
    image: ghcr.io/nabeken/docker-smtp-sink:action-local-test
    volumes:
      - vol:/sink
    ports:
      - "10025:10025"
    command: ["-v", "-h", "mx.example.com", "-m", "100", "-d", "/sink/", ":10025", "100"]

volumes:
  vol:
