services:
  rsync:
    image: ghcr.io/nabeken/docker-volume-container-rsync:latest@sha256:2fcf0bca7ddd71e101f7e26224fbbe43d3c14213b05c33f4073d34bc6c1b4309
    volumes:
      - vol:/docker
    ports:
      - "10873:873"

  sink:
    image: ghcr.io/nabeken/docker-smtp-sink:action-local-test
    volumes:
      - vol:/sink
    ports:
      - "10025:10025"
    command: ["-v", "-h", "mx.example.com", "-m", "100", "-d", "/sink/", ":10025", "100"]

volumes:
  vol:
