services:
  rsync:
    image: ghcr.io/nabeken/docker-volume-container-rsync:latest@sha256:c7fc01d081b6c976e781d854568a97e28b76614802c8e5173c2a9405c916bb8a
    volumes:
      - vol:/docker
    ports:
      - "10873:873"

  sink:
    image: ghcr.io/nabeken/docker-smtp-sink:action-local-test
    volumes:
      - vol:/sink
    ports:
      - "10025:10025"
    command: ["-v", "-h", "mx.example.com", "-m", "100", "-d", "/sink/", ":10025", "100"]

volumes:
  vol:
