services:
  rsync:
    image: ghcr.io/nabeken/docker-volume-container-rsync:latest@sha256:bc0753560ef64f8dd227d373c39be045f755b3f839374380cc6b50332aa31982
    volumes:
      - vol:/docker
    ports:
      - "10873:873"

  sink:
    image: ghcr.io/nabeken/docker-smtp-sink:action-local-test
    volumes:
      - vol:/sink
    ports:
      - "10025:10025"
    command: ["-v", "-h", "mx.example.com", "-m", "100", "-d", "/sink/", ":10025", "100"]

volumes:
  vol:
