services:
  rsync:
    image: ghcr.io/nabeken/docker-volume-container-rsync:latest@sha256:59616d239fe9e9696dd5058e04d5c0c385932fdc0cfc012d13426f2bb3bdc29a
    volumes:
      - vol:/docker
    ports:
      - "10873:873"

  sink:
    image: ghcr.io/nabeken/docker-smtp-sink:action-local-test
    volumes:
      - vol:/sink
    ports:
      - "10025:10025"
    command: ["-v", "-h", "mx.example.com", "-m", "100", "-d", "/sink/", ":10025", "100"]

volumes:
  vol:
