services:
  rsync:
    image: ghcr.io/nabeken/docker-volume-container-rsync:latest@sha256:3d523b5e3879cc5f100b1fe03f380b67347518d4863c2a2a23d4de5230a206e8
    volumes:
      - vol:/docker
    ports:
      - "10873:873"

  sink:
    image: ghcr.io/nabeken/docker-smtp-sink:action-local-test
    volumes:
      - vol:/sink
    ports:
      - "10025:10025"
    command: ["-v", "-h", "mx.example.com", "-m", "100", "-d", "/sink/", ":10025", "100"]

volumes:
  vol:
