services:
  rsync:
    image: ghcr.io/nabeken/docker-volume-container-rsync:latest@sha256:ba429d3a5a4c048d480343c5cd7530723065e8c2f3286fdd743a717b08b91727
    volumes:
      - vol:/docker
    ports:
      - "10873:873"

  sink:
    image: ghcr.io/nabeken/docker-smtp-sink:action-local-test
    volumes:
      - vol:/sink
    ports:
      - "10025:10025"
    command: ["-v", "-h", "mx.example.com", "-m", "100", "-d", "/sink/", ":10025", "100"]

volumes:
  vol:
