services:
  rsync:
    image: ghcr.io/nabeken/docker-volume-container-rsync:latest@sha256:da1c2d17eff65ea092072e087a35a0770fac1c33103dba8959a43d871b680fd0
    volumes:
      - vol:/docker
    ports:
      - "10873:873"

  sink:
    image: ghcr.io/nabeken/docker-smtp-sink:action-local-test
    volumes:
      - vol:/sink
    ports:
      - "10025:10025"
    command: ["-v", "-h", "mx.example.com", "-m", "100", "-d", "/sink/", ":10025", "100"]

volumes:
  vol:
