services:
  rsync:
    image: ghcr.io/nabeken/docker-volume-container-rsync:latest@sha256:8bfbd1cc257d66e48ae21f6f4c318a26cfe0086641701752d647fec563a8af41
    volumes:
      - vol:/docker
    ports:
      - "10873:873"

  sink:
    image: ghcr.io/nabeken/docker-smtp-sink:action-local-test
    volumes:
      - vol:/sink
    ports:
      - "10025:10025"
    command: ["-v", "-h", "mx.example.com", "-m", "100", "-d", "/sink/", ":10025", "100"]

volumes:
  vol:
