services:
  rsync:
    image: ghcr.io/nabeken/docker-volume-container-rsync:latest@sha256:0f8587024f00a3e420f036725243200d7ed26fe3faae7bfee8a5ee7fddc370b9
    volumes:
      - vol:/docker
    ports:
      - "10873:873"

  sink:
    image: ghcr.io/nabeken/docker-smtp-sink:action-local-test
    volumes:
      - vol:/sink
    ports:
      - "10025:10025"
    command: ["-v", "-h", "mx.example.com", "-m", "100", "-d", "/sink/", ":10025", "100"]

volumes:
  vol:
